version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8080:80
      - 1234:443
    volumes:
      - ./PatientDb.db:/app/patient.db
